version: 0.2.{build}
image: Visual Studio 2019
configuration: Release
init:
  - git config --global core.autocrlf false
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - PandocFilters/

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: dotnet restore PandocFilters.sln
- cmd: choco install pandoc

build:
  project: PandocFilters.sln

matrix:
  fast_finish: true

artifacts:
  - path: PandocFilters\bin\Release\*.nupkg
    type: NuGetPackage
  - path: PandocFilters\bin\Release\*.snupkg
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: cQKfyN4nusafedPIczoq8LqbW5wSCTTXG8CbcrwQcaglRj2zq9aRSaQX5KM+VEKd
    artifact: /.*(\.|\.s)nupkg/
