version: 0.3.{build}
image: Visual Studio 2022
configuration: Release
init:
  - git config --global core.autocrlf false
branches:
  only:
    - main
skip_tags:  true
only_commits:
  files:
    - PandocFilters/
    - appveyor.yml

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- cmd: dotnet restore PandocFilters.sln

build:
  project: PandocFilters.sln

matrix:
  fast_finish: true

before_test:
- cmd: choco install pandoc

artifacts:
  - path: PandocFilters\bin\Release\*.nupkg
    type: NuGetPackage
  - path: PandocFilters\bin\Release\*.snupkg
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: zx85vOF0s9eyYOVwT/6GJKE85T8SoWzZjbN8DyUtJ8pvOtiYz/XO94EmCaDgQCki
    artifact: /.*(\.|\.s)nupkg/
